baseURL: https://vivianvanoosten.netlify.app
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I AM AN AMBITIOUS LBS STUDENT, PASSIONATE ABOUT USING DATA IN 
      DECISIONMAKING
    title: Hi, my name is Vivian
  blog: {}
  #contact:
    #address:
    #  - city:
    #    country: 
    #    street: 
    #    title: Address
  #  buttonClear: Clear
  #  buttonSend: Send message
  #  email:
  #    - email:
  #      title: Email
  #  enable: yes
  #  phone:
  #    - phone:
  #      title: Phone
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Vivian van Oosten
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/vivianvanoosten/
      - icon: fa-github
        label: GitHub
        url: https://github.com/VivianvanOosten/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/vivian-van-oosten-lbs/
  image: 
  name: Vivian van Oosten
  navigation:
    button1:
      - name: Get Started
        url: blogs
    #button2:
    #  - name: Log In
    #    url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Most recent project
        url: blogs/directors
      - name: About me
        url: blogs/about_me
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: tree.JPG
        subtitle: 
        title: My CV
        url: docs/CV.pdf
      - image: lbs.jpg
        subtitle: Short introduction to Vivian
        title: About Me
        url: blogs/about_me
      - image: wine_glass2.jpeg
        subtitle: Predicting quality of wine based on chemical properties
        title: Wine Quality
        url: blogs/wine
      - image: movies.jpeg
        subtitle: Comparing Steven Spielberg and Tim Burton
        title: Director ratings
        url: blogs/directors
      - image: spotify.jpeg
        subtitle: Spotify Danceability Regression (R-Shiny app)
        title: Danceability
        url: blogs/spotify
    #  - image: pic05.jpg
    #    subtitle: Ipsum Dolor Sit Amet
    #    title: Consequat
    #    url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: No
    subtitle: "Welcome to my portfolio website! This is made to showcase my work 
    of the past few years and provide you with some insights into my way of working.
    It also contains the link to my linkedin if you're looking to learn more about me."
    title: Quick introduction
    url: blogs
